CREATE TABLE app_users (
    id uuid PRIMARY KEY,
    email varchar(320) NOT NULL,
    password_hash varchar(100) NOT NULL,
    display_name varchar(120) NOT NULL,
    timezone varchar(64) NOT NULL DEFAULT 'Africa/Casablanca',
    locale varchar(16) NOT NULL DEFAULT 'en',
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    last_login_at timestamptz,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_app_users_email UNIQUE (email),
    CONSTRAINT ck_app_users_email_lowercase CHECK (email = lower(email))
);

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID char(36) NOT NULL,
    SESSION_ID char(36) NOT NULL,
    CREATION_TIME bigint NOT NULL,
    LAST_ACCESS_TIME bigint NOT NULL,
    MAX_INACTIVE_INTERVAL integer NOT NULL,
    EXPIRY_TIME bigint NOT NULL,
    PRINCIPAL_NAME varchar(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID char(36) NOT NULL,
    ATTRIBUTE_NAME varchar(200) NOT NULL,
    ATTRIBUTE_BYTES bytea NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

